export const articles = [
  {
    id: 1,
    title: 'Hispatology of Alchool-Related Liver Diseases',
    author: 'Roth NC',
    releaseDate: 'FEB 2019',
    argument: 'Clinics in liver disease',
    description:
      'Excessive alchool consumption can lead to a spectrum of liver hispatology including Lorem ipsum dolor sit amet, consectetur adipisci elit, sed do eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullamco laboriosam, nisi ut aliquid ex ea commodi consequatur. Duis aute irure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    updated: new Date('2023-03-20T14:30:00.000Z'),
    citations: 9,
    references: 50,
    totalDownloads: '594',
    peerReviewd: false,
    fullArticle: false,
    metaAnalysis: false,
  },
  {
    id: 2,
    title: 'Reumatologic Diseases and the Liver',
    author: 'Schlenker, C Haltermen',
    releaseDate: 'JUNE 2019',
    argument: 'Clinics in liver disease',
    description:
      'Rheumatologic diseases such as rheumatoid arthritis, systemic lupus erythematosus, Sjogren syndrome, and scleroderma are immunologically mediated disorder that typically have mmultisystem involvment. Althrought clinically significant liver involvment is rare, liver enzyme abnormalities may be observed in up to 43% of patient. The biochemical abnormalities are typically mid and transient',
    updated: new Date('2023-03-17T10:30:00.000Z'),
    citations: 88,
    references: 23,
    totalDownloads: '124',
    peerReviewd: true,
    fullArticle: true,
    metaAnalysis: false,
  },
  {
    id: 3,
    number: 3,
    title: 'Hepatic Outcomes of Nonalcoholic Fatty Liver Disease',
    author: 'Saleh A. Alqahtani',
    releaseDate: 'FEB 2022',
    argument: 'Clinics in liver disease',
    description:
      'The standard definition of NAFLD is evidence of hepatic steatosis, defined by liver biopsy or imaging as the presence of greater than 5% hepatocyte triglyceride accumulation after excluding secondary causes of hepatic steatosis, such as harmful alcohol consumption, viral hepatitis, exposure to steatogenic medications, or hereditary disorders.8 NAFLD has a broad disease spectrum, from nonalcoholic fatty liver (NAFL) or simple steatosis to NASH, which is associated with liver fibrosis and can',
    updated: new Date('2022-02-01T08:00:00.000Z'),
    citations: 3,
    references: 67,
    totalDownloads: '364',
    peerReviewd: false,
    fullArticle: true,
    metaAnalysis: false,
  },
  {
    id: 4,
    title: 'Genetic Markers Predisposing to Nonalcoholic Steatohepatitis',
    author: 'Winston Dunn',
    releaseDate: 'JULY 1999',
    argument: 'Clinics in liver disease',
    description:
      'Because of the growing prevalence of NAFLD, the role of genetic markers in the progression of this disease needs to be understood. At this time, the management of NAFLD includes lifestyle management and managing the comorbidities related to metabolic syndrome. However, with the growing knowledge of the genetic markers, patients who are at high risk of progression can be identified early. Also, potential therapeutic targets directed against these genetic markers can be studied and will be',
    updated: new Date('2023-03-16T16:45:00.000Z'),
    citations: 6,
    references: 27,
    totalDownloads: '334',
    peerReviewd: true,
    fullArticle: false,
    metaAnalysis: true,
  },
  {
    id: 5,
    title: 'Economic Burden and Patient-Reported Outcomes',
    author: 'Maria Stepanova',
    releaseDate: 'SEP 2017',
    argument: 'Clinics in liver disease',
    description:
      'Health-related quality of life (HRQL) is a multidimensional construct that can comprehensively evaluate patient’s health status including but not limited to: physical, emotional, mental, and social well-being. Although the terms HRQL and patient-reported outcomes (PROs) have often been used interchangeably, PRO is a more inclusive term that includes not only HRQL but also other outcomes reported by and important to patients such as perceived fatigue, limitations in work productivity and daily',
    updated: new Date('2023-03-08T13:15:00.000Z'),
    citations: 7,
    references: 12,
    totalDownloads: '724',
    peerReviewd: false,
    fullArticle: true,
    metaAnalysis: false,
  },
  {
    id: 6,
    title: 'Aducanumab: evidence from clinical trial data and controversies',
    author: 'Rajesh R Tampi',
    releaseDate: 'OCT 2021',
    argument: 'Alzheimer disease',
    description:
      'Alzheimer’s disease (AD) is the most common cause for dementia worldwide. Until recently, all approved treatments for AD were symptomatic and not disease modifying. On 7 June 2021, the US FDA approved aducanumab, a human IgG1 anti-Aβ monoclonal antibody selective for Aβ aggregates, as the first disease-modifying treatment for AD. Aducanumab is approved in the United States for the treatment of mild cognitive impairment or mild-dementia stage of AD. In this Editorial, we review the trial data for aducanumab in the treatment of AD and the controversies that its approval has generated.',
    updated: new Date('2022-08-08T13:15:00.000Z'),
    citations: 8,
    references: 33,
    totalDownloads: '724',
    peerReviewd: true,
    fullArticle: true,
    metaAnalysis: false,
  },
  {
    id: 7,
    title: 'Weekly treatment with SAMiRNA ameliorates androgenetic alopecia',
    author: 'Sung-Il Yun',
    releaseDate: 'JAN 2022',
    argument: 'Androgenetic Alopecia',
    description:
      'Androgenetic alopecia (AGA) is the most common type of hair loss in men and women. Dihydrotestosterone (DHT) and androgen receptor (AR) levels are increased in patients with AGA, and DHT-AR signaling correlates strongly with AGA pathogenesis. In this study, treatment with self-assembled micelle inhibitory RNA (SAMiRNA) nanoparticle-type siRNA selectively suppressed AR expression in vitro. Clinical studies with application of SAMiRNA to the scalp and massaging to deliver it to the hair follicle confirmed its efficacy in AGA.',
    updated: new Date('2022-01-07T13:15:00.000Z'),
    citations: 8,
    references: 33,
    totalDownloads: '724',
    peerReviewd: true,
    fullArticle: true,
    metaAnalysis: true,
  },
  {
    id: 8,
    title:
      'Efficacy of GLP-1 RA Approved for Weight Management in Patients With or Without Diabetes',
    author: 'Mojca Jensterle',
    releaseDate: 'MAY 2022',
    argument: 'Weight Management',
    description:
      'The approval of once daily liraglutide, 3.0 mg, and once weekly semaglutide, 2.4 mg, for chronic weight management provides a novel effective strategy against obesity. The reliable models that might predict weight reducing potential at the individual level have not been identified yet',
    updated: new Date('2022-07-06T13:15:00.000Z'),
    citations: 8,
    references: 33,
    totalDownloads: '724',
    peerReviewd: false,
    fullArticle: true,
    metaAnalysis: false,
  },
];

export default articles;
