// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiAssistantConversation } from '../../../../docs-website/src/app/pages/patterns/ai-assistant/examples/ai-assistant-conversation.example';

const meta: Meta = {
  title: 'Patterns/AI assistant',
  component: AiAssistantConversation.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'A conversational assistant: a thread of user and assistant message cards, a streaming answer announced to assistive technology, per-answer feedback, and a docked composer — built on the Helix AI avatar and gradient. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
