// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiChatHistoryPanel } from '../../../../docs-website/src/app/pages/patterns/ai-chat-history/examples/ai-chat-history-panel.example';

const meta: Meta = {
  title: 'Patterns/AI chat history',
  component: AiChatHistoryPanel.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'A panel of past AI conversations, grouped by recency and titled by their first question, that the user can reopen, rename and delete — with real loading, empty and error states, not just the happy path. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
