// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiEntryPointsSurfaces } from '../../../../docs-website/src/app/pages/patterns/ai-entry-points/examples/ai-entry-points-surfaces.example';

const meta: Meta = {
  title: 'Patterns/AI entry points',
  component: AiEntryPointsSurfaces.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'Where and how the user reaches AI — a header/rail trigger, a floating action button, and a one-time promo banner — all wearing the same Helix AI treatment so AI is recognisable and leads to one assistant surface. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
