// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiGenerateFieldRewrite } from '../../../../docs-website/src/app/pages/patterns/ai-generate-field/examples/ai-generate-field-rewrite.example';

const meta: Meta = {
  title: 'Patterns/AI generate & rewrite',
  component: AiGenerateFieldRewrite.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'A one-shot AI action on a single field — draft, rewrite, shorten, fix — that proposes new text the user reviews and accepts, discards or regenerates, with an undo. Not a conversation. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
