// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiGenerationTrace } from '../../../../docs-website/src/app/pages/patterns/ai-generation-trace/examples/ai-generation-trace-trace.example';

const meta: Meta = {
  title: 'Patterns/AI generation trace',
  component: AiGenerationTrace.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'A collapsed "How was this generated?" disclosure under an AI answer, showing the steps the assistant took and the inputs it used — so users can understand and trust the result. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
