// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiInlineActions } from '../../../../docs-website/src/app/pages/patterns/ai-inline-actions/examples/ai-inline-actions-actions.example';

const meta: Meta = {
  title: 'Patterns/Inline AI actions',
  component: AiInlineActions.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'Bring the assistant to the content: AI actions (summarise, explain, ask about this) attached to a document or a selection, with the result shown in place or sent to the assistant — not a detour to a separate chat. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
