// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiPromptStartersHome } from '../../../../docs-website/src/app/pages/patterns/ai-prompt-starters/examples/ai-prompt-starters-home.example';

const meta: Meta = {
  title: 'Patterns/AI prompt starters',
  component: AiPromptStartersHome.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          "The pre-conversation landing for an assistant: a short greeting, a few suggested-prompt cards that seed the composer, and the composer itself — so the user isn't facing a blank box. See the full pattern guidance in the docs site.",
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
