// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiSourcesCitations } from '../../../../docs-website/src/app/pages/patterns/ai-sources/examples/ai-sources-citations.example';

const meta: Meta = {
  title: 'Patterns/AI sources & citations',
  component: AiSourcesCitations.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'Make an AI answer traceable — number claims with inline citations that reveal the cited passage and link to the source, and list the ranked source documents behind the answer, collapsed past a handful. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
