// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AiUsageLimits } from '../../../../docs-website/src/app/pages/patterns/ai-usage-limits/examples/ai-usage-limits-limits.example';

const meta: Meta = {
  title: 'Patterns/AI usage & limits',
  component: AiUsageLimits.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          "Tell the user where they stand against AI limits — responses left, a context that's too long, a rate limit — before and when they hit them, with a clear way forward, using hlx-notification. See the full pattern guidance in the docs site.",
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
