// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { AppShellBasic } from '../../../../docs-website/src/app/pages/patterns/app-shell/examples/app-shell-basic.example';

const meta: Meta = {
  title: 'Patterns/App shell',
  component: AppShellBasic.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'The standard page chrome — Helix header with product name, primary navigation and global actions, a routed content area, and the footer — assembled once and driven by typed route data. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
