// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { ChartsHighcharts } from '../../../../docs-website/src/app/pages/patterns/charts/examples/charts-highcharts.example';

const meta: Meta = {
  title: 'Patterns/Charts',
  component: ChartsHighcharts.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'Build charts with the Helix Highcharts styled-mode theme so colour, type and axes come from the design system — never a hardcoded palette — and keep them accessible and readable. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
