// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { DataGridHelix } from '../../../../docs-website/src/app/pages/patterns/data-grid/examples/data-grid-helix.example';

const meta: Meta = {
  title: 'Patterns/Data grid wrapper',
  component: DataGridHelix.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'One place to set up AG Grid the Helix way — modules and licence registered once, a Theming-API theme built from Helix tokens, shared column defaults, and column-state persistence. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
