// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { DialogsConfirmDestructive } from '../../../../docs-website/src/app/pages/patterns/dialogs/examples/dialogs-confirm-destructive.example';

const meta: Meta = {
  title: 'Patterns/Dialogs/Confirm a destructive action',
  component: DialogsConfirmDestructive.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'A modal for one decision or one short task. Open it through a named size preset, structure the body with the Material dialog slots, and put the primary action on the right. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
