// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { EntityDetailSnapshot } from '../../../../docs-website/src/app/pages/patterns/entity-detail/examples/entity-detail-snapshot.example';

const meta: Meta = {
  title: 'Patterns/Entity detail',
  component: EntityDetailSnapshot.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'A record page: an entity header, a summary card of the key facts, then an accordion of sections that load lazily and are disabled when they have nothing to show. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
