// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { ErrorPagesStates } from '../../../../docs-website/src/app/pages/patterns/error-pages/examples/error-pages-states.example';

const meta: Meta = {
  title: 'Patterns/Error pages',
  component: ErrorPagesStates.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'Full-page states for 404, 403 and 500 — a centred hlx-empty-state with a pictogram, a plain explanation and one clear way forward, served by the router. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
