// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { ExportSnackbar } from '../../../../docs-website/src/app/pages/patterns/export/examples/export-snackbar.example';

const meta: Meta = {
  title: 'Patterns/Export',
  component: ExportSnackbar.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          "An export action: pick a format, then give asynchronous feedback through snackbars — preparing, then ready (or failed with retry) — so the user isn't left staring at a frozen button. See the full pattern guidance in the docs site.",
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
