// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { FormsBorderless } from '../../../../docs-website/src/app/pages/patterns/forms/examples/forms-borderless.example';

const meta: Meta = {
  title: 'Patterns/Form layout/Borderless field variant',
  component: FormsBorderless.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'A single-column form of Material fields grouped into sections, with inline validation on blur, a required/optional convention, and a docked action bar — laid out with Helix spacing tokens. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
