// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { ListWithFiltersPage } from '../../../../docs-website/src/app/pages/patterns/list-with-filters/examples/list-with-filters-page.example';

const meta: Meta = {
  title: 'Patterns/List with filters',
  component: ListWithFiltersPage.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'A results page: a toolbar with search and filters, the applied filters shown as removable chips, and a results table that handles its own loading, empty and error states. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
