// GENERATED by tools/patterns/generate-storybook-stories.mjs — do not edit.
import type { Meta, StoryObj } from '@storybook/angular';

// Patterns stories reuse the docs-website pattern examples as the single source,
// so they reach across the project boundary on purpose.
// eslint-disable-next-line @nx/enforce-module-boundaries
import { PageStatesAsyncSwitch } from '../../../../docs-website/src/app/pages/patterns/page-states/examples/page-states-async-switch.example';

const meta: Meta = {
  title: 'Patterns/Page states/All four states with @switch',
  component: PageStatesAsyncSwitch.dynamicComponent,
  parameters: {
    docs: {
      description: {
        component:
          'Every region that loads data has four states — loading, loaded, empty and error. Design all four from the start so a screen never shows a blank box or a frozen spinner. See the full pattern guidance in the docs site.',
      },
    },
  },
};

export default meta;
type Story = StoryObj;

export const Overview: Story = {};
