import type Highcharts from 'highcharts';
export declare const CDX_FONT_FAMILY = "\"Source Sans Pro\", sans-serif";
export declare const CDX_MATERIAL_THEME_COLORS: string[];
export declare const CDX_BRAND_PRIMARY_COLORS: string[];
export declare const CDX_BRAND_PRIMARY_HOVER_COLORS: string[];
export declare const CDX_BRAND_SECONDARY_COLORS: string[];
export declare const CDX_BRAND_SECONDARY_HOVER_COLORS: string[];
export declare const CDX_BRAND_TERTIARY_COLORS: string[];
export declare const CDX_BRAND_TERTIARY_HOVER_COLORS: string[];
export declare const HIGHCHARTS_CDX_THEME: Highcharts.Options;
export declare const HIGHCHARTS_CDX_SECONDARY_THEME: Highcharts.Options;
export declare const HIGHCHARTS_CDX_TERTIARY_THEME: Highcharts.Options;
