export interface NavigationItem {
  title: string;
  route: string;
}

// Mirrors the left navigation of each section; keep in sync when adding pages.

const foundationsNavigationMap: NavigationItem[] = [
  {
    title: 'Principles & foundations',
    route: '/foundations/principles-and-foundations',
  },
  { title: 'Color', route: '/foundations/color' },
  { title: 'Typography', route: '/foundations/typography' },
  { title: 'Iconography', route: '/foundations/iconography' },
  { title: 'Branding', route: '/foundations/branding' },
  { title: 'Elevation', route: '/foundations/elevation' },
  { title: 'Density', route: '/foundations/density' },
  { title: 'AI', route: '/foundations/ai' },
];

const developmentNavigationMap: NavigationItem[] = [
  {
    title: 'Getting Started Overview',
    route: '/development/getting-started-overview',
  },
  {
    title: 'Quick Start New Project',
    route: '/development/quick-start-new-project',
  },
  { title: 'Color tokens', route: '/development/colors' },
  { title: 'Typography tokens', route: '/development/typography' },
  { title: 'Elevation tokens', route: '/development/elevation' },
  { title: 'Density tokens', route: '/development/density' },
  {
    title: 'Responsive Development',
    route: '/development/responsive-development',
  },
  { title: 'Migration Guide', route: '/development/migration-guide' },
  { title: 'Release Notes', route: '/development/release-notes' },
];

const componentsNavigationMap: NavigationItem[] = [
  { title: 'Component overview', route: '/components/components-overview' },
  { title: 'Autocomplete', route: '/components/autocomplete' },
  { title: 'Badge', route: '/components/badge' },
  { title: 'Breadcrumbs', route: '/components/breadcrumbs' },
  { title: 'Button', route: '/components/buttons' },
  { title: 'Button - FAB', route: '/components/fab' },
  { title: 'Button - Icon button', route: '/components/icon-button' },
  { title: 'Button toggle', route: '/components/button-toggle' },
  { title: 'Card', route: '/components/card' },
  { title: 'Checkbox', route: '/components/checkbox' },
  { title: 'Chip', route: '/components/chips' },
  { title: 'Data grid', route: '/components/data-grid' },
  { title: 'Date picker', route: '/components/date-picker' },
  { title: 'Dialog', route: '/components/dialog' },
  { title: 'Divider', route: '/components/divider' },
  {
    title: 'Expansion panel (accordion)',
    route: '/components/expansion-panel',
  },
  { title: 'Footer', route: '/components/footer' },
  { title: 'Form field', route: '/components/form-field' },
  { title: 'Header', route: '/components/header' },
  { title: 'Highcharts', route: '/components/highcharts' },
  { title: 'Hyperlink', route: '/components/hyperlink' },
  { title: 'Icon', route: '/components/icons' },
  { title: 'Input (text field)', route: '/components/text-input' },
  { title: 'List', route: '/components/list' },
  { title: 'Menu', route: '/components/menu' },
  { title: 'Notifications', route: '/components/notifications' },
  { title: 'Paginator', route: '/components/paginator' },
  { title: 'Progress bar', route: '/components/progress-bar' },
  { title: 'Progress spinner', route: '/components/progress-spinner' },
  { title: 'Radio button', route: '/components/radio-button' },
  { title: 'Select', route: '/components/select' },
  { title: 'Sidenav (Navigation drawer)', route: '/components/sidenav' },
  { title: 'Skeleton loader', route: '/components/skeleton-loader' },
  { title: 'Slide toggle (switch)', route: '/components/slide-toggle' },
  { title: 'Slider', route: '/components/slider' },
  { title: 'Snackbar', route: '/components/snackbar' },
  { title: 'Sort header', route: '/components/sort-header' },
  { title: 'Stepper', route: '/components/stepper' },
  { title: 'Table and data grid', route: '/components/table' },
  { title: 'Tabs', route: '/components/tabs' },
  { title: 'Text area', route: '/components/text-area' },
  { title: 'Time picker', route: '/components/time-picker' },
  { title: 'Toolbar', route: '/components/toolbar' },
  { title: 'Tooltip', route: '/components/tooltips' },
  { title: 'Tree', route: '/components/tree' },
];

const patternsNavigationMap: NavigationItem[] = [
  { title: 'Filters pattern', route: '/patterns/filters' },
  { title: 'Basic filters', route: '/patterns/filters/basic-filters' },
  { title: 'Filter modal', route: '/patterns/filters/filter-modal' },
  { title: 'Filter panel', route: '/patterns/filters/filter-panel' },
  { title: 'Sidebar pattern', route: '/patterns/sidebar' },
  {
    title: 'Header with navigation and sidebar',
    route: '/patterns/sidebar/header-with-navigation',
  },
  { title: 'Nested navigation', route: '/patterns/sidebar/nested-navigation' },
  {
    title: 'Products working best with sidebar',
    route: '/patterns/sidebar/products',
  },
  { title: 'Page states', route: '/patterns/page-states' },
  { title: 'Empty state', route: '/patterns/page-states' },
  { title: 'Error state', route: '/patterns/page-states' },
  { title: 'Loading skeleton', route: '/patterns/page-states' },
  { title: 'Dialogs', route: '/patterns/dialogs' },
  { title: 'Confirm dialog', route: '/patterns/dialogs' },
  { title: 'Side panel dialog', route: '/patterns/dialogs' },
  { title: 'App shell', route: '/patterns/app-shell' },
  { title: 'Layout', route: '/patterns/app-shell' },
  { title: 'Responsive navigation', route: '/patterns/app-shell' },
  { title: 'List with filters', route: '/patterns/list-with-filters' },
  { title: 'Results page', route: '/patterns/list-with-filters' },
  { title: 'Filter chips', route: '/patterns/list-with-filters' },
  { title: 'AI assistant', route: '/patterns/ai-assistant' },
  { title: 'Chat', route: '/patterns/ai-assistant' },
  { title: 'Conversation', route: '/patterns/ai-assistant' },
  { title: 'Streaming', route: '/patterns/ai-assistant' },
  { title: 'AI prompt starters', route: '/patterns/ai-prompt-starters' },
  { title: 'Assistant home', route: '/patterns/ai-prompt-starters' },
  { title: 'Suggested prompts', route: '/patterns/ai-prompt-starters' },
  { title: 'AI generation trace', route: '/patterns/ai-generation-trace' },
  { title: 'How was this generated', route: '/patterns/ai-generation-trace' },
  { title: 'Reasoning disclosure', route: '/patterns/ai-generation-trace' },
  { title: 'AI usage and limits', route: '/patterns/ai-usage-limits' },
  { title: 'Quota', route: '/patterns/ai-usage-limits' },
  { title: 'Context limit', route: '/patterns/ai-usage-limits' },
  { title: 'Inline AI actions', route: '/patterns/ai-inline-actions' },
  { title: 'Summarize', route: '/patterns/ai-inline-actions' },
  { title: 'Ask AI about this', route: '/patterns/ai-inline-actions' },
  { title: 'AI generate and rewrite', route: '/patterns/ai-generate-field' },
  { title: 'Rewrite with AI', route: '/patterns/ai-generate-field' },
  { title: 'One-shot generation', route: '/patterns/ai-generate-field' },
  { title: 'Data grid wrapper', route: '/patterns/data-grid' },
  { title: 'AG Grid', route: '/patterns/data-grid' },
  { title: 'Grid persistence', route: '/patterns/data-grid' },
  { title: 'Charts', route: '/patterns/charts' },
  { title: 'Highcharts', route: '/patterns/charts' },
  { title: 'Data visualization', route: '/patterns/charts' },
  { title: 'Form layout', route: '/patterns/forms' },
  { title: 'Forms', route: '/patterns/forms' },
  { title: 'Validation', route: '/patterns/forms' },
  { title: 'Entity detail', route: '/patterns/entity-detail' },
  { title: 'Snapshot', route: '/patterns/entity-detail' },
  { title: 'Record page', route: '/patterns/entity-detail' },
  { title: 'Export', route: '/patterns/export' },
  { title: 'Download', route: '/patterns/export' },
  { title: 'Error pages', route: '/patterns/error-pages' },
  { title: '404', route: '/patterns/error-pages' },
  { title: '403', route: '/patterns/error-pages' },
  { title: '500', route: '/patterns/error-pages' },
];

const servicesNavigationMap: NavigationItem[] = [
  { title: 'Services Overview', route: '/services/services-overview' },
  { title: 'Analytics', route: '/services/analytics' },
  { title: 'Authentication', route: '/services/authentication' },
  {
    title: 'Session Activity Management',
    route: '/services/session-activity-management',
  },
  { title: 'OTI snippet', route: '/services/oti-snippet' },
  { title: 'Translations', route: '/services/translations' },
];

export const navigationMap: NavigationItem[] = [
  ...foundationsNavigationMap,
  ...developmentNavigationMap,
  ...componentsNavigationMap,
  ...patternsNavigationMap,
  ...servicesNavigationMap,
];
